- iast/views/documents.py
- iast/views/profile.py
[https://github.com/HXSecurity/DongTai/issues/173](https://github.com/HXSecurity/DongTai/issues/173)
> modify the default number of return items

- iast/utils.py
- iast/views/github_contributors.py
- iast/views/sca_sidebar_index.py
- iast/views/scas.py
- iast/views/vul_list_for_plugin.py
- iast/views/vul_sidebar_index.py
- iast/views/vuls.py
[https://github.com/HXSecurity/DongTai/issues/242](https://github.com/HXSecurity/DongTai/issues/242)
- Add order_by whitelist to avoid abnormal errors
- Add get_model_order_options function in iast/utils.py
> issue-242 Add order_by whitelist to avoid abnormal errors

- iast/serializers/vul.py
- iast/views/vul_list_for_plugin.py
[https://github.com/HXSecurity/DongTai/issues/252](https://github.com/HXSecurity/DongTai/issues/252)
> feature:HXSecurity/issue-252

- iast/views/api_route_search.py
- iast/views/engine_method_pool_search.py
- webapi/settings.py
[https://github.com/HXSecurity/DongTai/issues/248](https://github.com/HXSecurity/DongTai/issues/248)
> fix:HXSecurity/issue-248

- iast/serializers/agent.py
- iast/urls.py
- iast/views/agent_search.py
- iast/views/agent_start.py
- iast/views/agent_stop.py
- iast/views/api_route_related_request.py
- iast/views/api_route_search.py
- iast/views/engine_hook_rule_status.py
- iast/views/engine_method_pool_search.py
- iast/views/sca_summary.py
- iast/views/scas.py
- iast/views/vul_details.py
- iast/views/vul_summary.py
- iast/views/vuls.py
- webapi/settings.py
- encoding bugs
- egde case bugs
- authority bugs
[https://github.com/HXSecurity/DongTai/issues/260](https://github.com/HXSecurity/DongTai/issues/260)
> fix:HXSecurity/DongTai/issues/260

- iast/base/agent.py
[https://github.com/HXSecurity/DongTai-webapi/issues/186](https://github.com/HXSecurity/DongTai-webapi/issues/186)
> fix:Inconsistent statistics due to multiple versions of the project

- iast/views/engine_hook_rule_type_add.py
> Revert "fix:issue-190 add the corresponding creation strategy logic"

- iast/views/vul_details.py
https://github.com/HXSecurity/DongTai-webapi/issues/195
> Unreasonable escaping causes the text to display incorrectly

- iast/urls.py
- iast/views/sensitive_info_rule.py
[https://github.com/HXSecurity/DongTai-webapi/issues/188](https://github.com/HXSecurity/DongTai-webapi/issues/188)
> Sensitive information rule configuration

- iast/views/strategy_modified.py
- iast/views/strategys.py
- iast/views/strategys_add.py
Reverts HXSecurity/DongTai-webapi#207
> Revert "Feature issue200"

- iast/serializers/sca.py
- iast/urls.py
- iast/views/scan_strategys.py
Scan policy template management #247
> Scan policy template management #247

- iast/urls.py
- webapi/settings.py
- webapi/urls.py
Split the logic of importing the app
> Split the logic of importing the app to support extension

- conf/uwsgi.ini
Reverts HXSecurity/DongTai-webapi#340
> Revert "Update uwsgi.ini"

- .github/workflows/deploy_to_test.yml
Reverts HXSecurity/DongTai-webapi#341
> Revert "Update deploy_to_test.yml"

- deploy/deploy-dongtai-webapi-test.yml
Reverts HXSecurity/DongTai-webapi#352
> Revert "Update deploy-dongtai-webapi-test.yml"

- iast/base/agent.py
> optimise sql to reduce io times in vuln/summary

- iast/base/agent.py
- iast/urls.py
- iast/views/agent_download.py
- iast/views/sca_export.py
[https://github.com/HXSecurity/DongTai/issues/377](https://github.com/HXSecurity/DongTai/issues/377)
[https://github.com/HXSecurity/DongTai/issues/380](https://github.com/HXSecurity/DongTai/issues/380)
> a temporary sca export for issue-377&380

- README.ZH_CN.md
- README.md
Thanks for the addition on the jq part
@xzy9999
> Develop Document Update thanks for @xzy9999

- .github/workflows/deploy_to_test.yml
Reverts HXSecurity/DongTai-webapi#375
> Revert "Revert "Update deploy_to_test.yml""

- iast/views/sca_details.py
- webapi/settings.py
fix https://github.com/HXSecurity/DongTai/issues/402
> change sca from database to api

- webapi/settings.py
Reverts HXSecurity/DongTai-webapi#393
> Revert "Update settings.py"

- .github/workflows/deploy_to_test.yml
- conf/config.ini.test
Reverts HXSecurity/DongTai-webapi#376
> Revert "Revert "Revert "Update deploy_to_test.yml"""

- iast/views/logs.py
Reverts HXSecurity/DongTai-webapi#455
> Revert "optimise: logs api use cache to avoid count in every query"

- iast/serializers/vul.py
- iast/views/details_id.py
- iast/views/vuls.py
Reverts HXSecurity/DongTai-webapi#450
> Revert "optimise: vuln list serilizer query"
